force-app/main/default/objects/AWS_S3_Setting__mdt/AWS_S3_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Stores environment-specific AWS S3 configuration settings, including access credentials, bucket names, regions, and path details, used to generate presigned URLs for secure client-side file uploads.</description>
    <label>AWS S3 Setting</label>
    <pluralLabel>AWS S3 Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/AWS_S3_Setting__mdt/fields/Access_Key__c.field-meta.xml
<CustomField>
    <fullName>Access_Key__c</fullName>
    <description>The AWS access key ID used to authenticate requests and sign presigned URLs. This is part of the credential pair associated with an IAM user or role.</description>
    <inlineHelpText>The AWS access key ID used to authenticate requests and sign presigned URLs. This is part of the credential pair associated with an IAM user or role.</inlineHelpText>
    <label>Access Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_S3_Setting__mdt/fields/Bucket__c.field-meta.xml
<CustomField>
    <fullName>Bucket__c</fullName>
    <description>The name of the AWS S3 bucket where files will be uploaded or accessed. This must match the bucket configured in your AWS account.</description>
    <inlineHelpText>The name of the AWS S3 bucket where files will be uploaded or accessed. This must match the bucket configured in your AWS account.</inlineHelpText>
    <label>Bucket</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_S3_Setting__mdt/fields/File_Size_Limit_Mb__c.field-meta.xml
<CustomField>
    <fullName>File_Size_Limit_Mb__c</fullName>
    <description>System wide max file size upload allowed. (megabytes)</description>
    <inlineHelpText>System wide max file size upload allowed. (megabytes)</inlineHelpText>
    <label>File Size Limit Mb</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AWS_S3_Setting__mdt/fields/Identity_Pool_Id__c.field-meta.xml
<CustomField>
    <fullName>Identity_Pool_Id__c</fullName>
    <label>Identity Pool Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_S3_Setting__mdt/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Production</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AWS_S3_Setting__mdt/fields/Secret_Access_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Access_Key__c</fullName>
    <description>The AWS secret access key paired with the access key ID. This value is used to securely sign presigned URLs and must be kept confidential.</description>
    <inlineHelpText>The AWS secret access key paired with the access key ID. This value is used to securely sign presigned URLs and must be kept confidential.</inlineHelpText>
    <label>Secret Access Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3_File__c/S3_File__c.object-meta.xml
<CustomObject>
    <label>S3 File</label>
    <nameField>
        <displayFormat>S3-{000000}</displayFormat>
        <label>S3 File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S3 Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/S3_File__c/fields/Deleted__c.field-meta.xml
<CustomField>
    <fullName>Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Represents if the file has been deleted from S3.</description>
    <inlineHelpText>Represents if the file has been deleted from S3.</inlineHelpText>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/File_Extension__c.field-meta.xml
<CustomField>
    <fullName>File_Extension__c</fullName>
    <formula>IF(
  CONTAINS(File_Name__c, &quot;.&quot;),
  LOWER(
    /* Get all characters after the last dot */
    RIGHT(
      File_Name__c,
      FIND(
        &quot;.&quot;,
        /* Reverse the string to locate the first dot from the end */
        REVERSE(File_Name__c)
      ) - 1
    )
  ),
  &quot;&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>File Extension</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/File_Info__c.field-meta.xml
<CustomField>
    <fullName>File_Info__c</fullName>
    <formula>/* MONTH(LastModifiedDate) + &apos; &apos; + DAY(LastModifiedDate) + &apos;, &apos; + YEAR(LastModifiedDate) 
+ &apos; • &apos; +  Size_Label__c  
+ &apos; • &apos; + File_Extension__c

*/
if(ISBLANK(S3_File_Object__c), &apos;&apos;, S3_File_Object__c &amp; &apos; • &apos;) + 
CASE(MONTH(DATEVALUE(LastModifiedDate)),
  1, &quot;Jan&quot;,
  2, &quot;Feb&quot;,
  3, &quot;Mar&quot;,
  4, &quot;Apr&quot;,
  5, &quot;May&quot;,
  6, &quot;Jun&quot;,
  7, &quot;Jul&quot;,
  8, &quot;Aug&quot;,
  9, &quot;Sep&quot;,
  10, &quot;Oct&quot;,
  11, &quot;Nov&quot;,
  12, &quot;Dec&quot;,
  &quot;?&quot;
) &amp; &apos; &apos; &amp;
TEXT(DAY(DATEVALUE(LastModifiedDate))) &amp; &apos;, &apos; &amp;
TEXT(YEAR(DATEVALUE(LastModifiedDate))) &amp;
&apos; • &apos; &amp; Size_Label__c &amp;
&apos; • &apos; &amp; File_Extension__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>File Info</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/File_Last_Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>File_Last_Modified_Date__c</fullName>
    <formula>DATETIMEVALUE(&quot;1970-01-01 00:00:00&quot;) + ( VALUE(File_Last_Modified_Epoch__c) / 1000 / 86400)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>File Last Modified Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/File_Last_Modified_Epoch__c.field-meta.xml
<CustomField>
    <fullName>File_Last_Modified_Epoch__c</fullName>
    <description>Represents when the file was last modified. Number of seconds (or milliseconds) since Jan 1, 1970 00:00:00 UTC</description>
    <inlineHelpText>Represents when the file was last modified. Number of seconds (or milliseconds) since Jan 1, 1970 00:00:00 UTC</inlineHelpText>
    <label>File Last Modified Epoch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Unique identifier for a file (object) within a specific S3 bucket. It&apos;s essentially the full path to the object inside the bucket.</description>
    <inlineHelpText>Unique identifier for a file (object) within a specific S3 bucket. It&apos;s essentially the full path to the object inside the bucket.</inlineHelpText>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/Object_URL__c.field-meta.xml
<CustomField>
    <fullName>Object_URL__c</fullName>
    <description>Direct path to a specific file (object) stored in an Amazon S3 bucket.</description>
    <inlineHelpText>Direct path to a specific file (object) stored in an Amazon S3 bucket.</inlineHelpText>
    <label>Object URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <description>Id of related record.</description>
    <inlineHelpText>Id of related record.</inlineHelpText>
    <label>Parent Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/S3_Path__c.field-meta.xml
<CustomField>
    <fullName>S3_Path__c</fullName>
    <description>Path to file in S3.</description>
    <inlineHelpText>Path to file in S3.</inlineHelpText>
    <label>S3 Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/Size_Bytes__c.field-meta.xml
<CustomField>
    <fullName>Size_Bytes__c</fullName>
    <label>Size Bytes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/Size_Kilobytes__c.field-meta.xml
<CustomField>
    <fullName>Size_Kilobytes__c</fullName>
    <formula>TEXT(ROUND(VALUE(Size_Bytes__c) / 1024, 2))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Size Kilobytes</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/Size_Label__c.field-meta.xml
<CustomField>
    <fullName>Size_Label__c</fullName>
    <formula>IF(
    NOT(ISBLANK(Size_Megabytes__c)) &amp;&amp; VALUE(Size_Megabytes__c) &gt;= 1,
    TEXT(ROUND(VALUE(Size_Megabytes__c), 2)) &amp; &quot; MB&quot;,
    IF(
        NOT(ISBLANK(Size_Kilobytes__c)) &amp;&amp; VALUE(Size_Kilobytes__c) &gt;= 1,
        TEXT(ROUND(VALUE(Size_Kilobytes__c), 2)) &amp; &quot; KB&quot;,
        TEXT(ROUND(VALUE(Size_Bytes__c), 2)) &amp; &quot; B&quot;
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Size Label</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/Size_Megabytes__c.field-meta.xml
<CustomField>
    <fullName>Size_Megabytes__c</fullName>
    <formula>TEXT(ROUND(VALUE( Size_Kilobytes__c ) / 1024, 2))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Size Megabytes</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/sObject_Type__c.field-meta.xml
<CustomField>
    <fullName>sObject_Type__c</fullName>
    <description>Related to what salesforce object type.</description>
    <inlineHelpText>Related to what salesforce object type.</inlineHelpText>
    <label>sObject Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/Versions__c.field-meta.xml
<CustomField>
    <fullName>Versions__c</fullName>
    <description>Number of file versions.</description>
    <inlineHelpText>Number of file versions.</inlineHelpText>
    <label>Versions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/S3_File__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <label>Visibility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AWSS3Utilities.cls
/**
 * Utility class for AWS S3 operations in Salesforce.
 * Handles file upload, deletion, listing, and presigned URL generation.
*/
public without sharing class AWSS3Utilities {
    /**
     * Expiry time for presigned URLs (in seconds).
    */
    private Final static Integer PRESIGNED_URL_EXPIRES = 60;

    /**
     * Returns a presigned URL for viewing a file.
     * @param key S3 key for the file.
     * @return Presigned URL string.
    */
    @AuraEnabled
    public static String viewFile(String key) {
        
        // String url = createPresignedUrlForView(key);
        String method = 'GET';
        String url = createPresignedUrl(method, key);

        system.debug('view url');
        system.debug(url);

        return url;
    }

    /**
     * Returns a presigned URL for uploading a file.
     * @param key S3 key for the file.
     * @return Presigned URL string.
    */
    @AuraEnabled
    public static String postFile(String key) {

        // String url = createPresignedUrlForView(key);
        String method = 'PUT';
        String url = createPresignedUrl(method, key);

        system.debug('post url');
        system.debug(url);

        return url;
    }

    /**
     * Deletes a file from S3 and removes its record from Salesforce.
     * @param key S3 key for the file.
     * @param id Salesforce record Id for the file.
     * @return True if deleted successfully, false otherwise.
    */
    @AuraEnabled
    public static Boolean deleteFile(String key, String id){

        AWS_S3_Setting__mdt creds = getCreds('');

        String accessKey = creds.Access_Key__c;
        String secretKey = creds.Secret_Access_Key__c;
        String bucketName =  creds.Bucket__c;
        String bucketRegion = creds.Region__c; 

        Boolean isDeleted = false;

        try {
            Datetime currentDateTime = Datetime.now();
            String dateOnly = currentDateTime.formatGmt('yyyyMMdd');
            String xAmzDate = currentDateTime.formatGmt('yyyyMMdd\'T\'HHmmss\'Z\'');
            String credentialScope = dateOnly + '/' + bucketRegion + '/s3/aws4_request';
            String xAmzCredentialStr = accessKey + '/' + credentialScope;
            String xAmzSignedHeaders = 'host;x-amz-date';
            String host = bucketName + '.s3.' + bucketRegion + '.amazonaws.com';
    
            // Canonical request for DELETE
            String canonicalRequest =
                'DELETE\n' +
                UriEncode('/' + key, false) + '\n' +
                '\n' +
                'host:' + host + '\n' +
                'x-amz-date:' + xAmzDate + '\n' +
                '\n' +
                'host;x-amz-date\n' +
                'UNSIGNED-PAYLOAD';
    
            // String to sign
            String stringToSign = 'AWS4-HMAC-SHA256\n' +
                xAmzDate + '\n' +
                credentialScope + '\n' +
                EncodingUtil.convertToHex(Crypto.generateDigest('SHA-256', Blob.valueOf(canonicalRequest)));
    
            // Generate the signing key
            Blob dateKey = Crypto.generateMac('hmacSHA256', Blob.valueOf(dateOnly), Blob.valueOf('AWS4' + secretKey));
            Blob dateRegionKey = Crypto.generateMac('hmacSHA256', Blob.valueOf(bucketRegion), dateKey);
            Blob dateRegionServiceKey = Crypto.generateMac('hmacSHA256', Blob.valueOf('s3'), dateRegionKey);
            Blob signingKey = Crypto.generateMac('hmacSHA256', Blob.valueOf('aws4_request'), dateRegionServiceKey);
    
            // Generate the signature
            Blob signature = Crypto.generateMac('hmacSHA256', Blob.valueOf(stringToSign), signingKey);
            String signatureStr = EncodingUtil.convertToHex(signature);
    
            // Create and send the HTTP request
            HttpRequest httpRequest = new HttpRequest();
                httpRequest.setMethod('DELETE');
                httpRequest.setEndpoint('https://' + host + '/' + UriEncode(key, true));
                httpRequest.setHeader('Authorization', 'AWS4-HMAC-SHA256 Credential=' + accessKey + '/' + credentialScope + ', SignedHeaders=' + xAmzSignedHeaders + ', Signature=' + signatureStr);
                httpRequest.setHeader('x-amz-date', xAmzDate);
                httpRequest.setHeader('x-amz-content-sha256', 'UNSIGNED-PAYLOAD');
    
            Http http = new Http();
            HttpResponse res = http.send(httpRequest);

            system.debug(res.getStatusCode() + ' ' + res.getStatus());
            system.debug(res.getBody());
    
            if (res.getStatusCode() == 204) { // 204 No Content means the deletion was successful
                isDeleted = true;

                S3_File__c s3FileToDelete = new S3_File__c();
                    s3FileToDelete.Id = id;
                    s3FileToDelete.Deleted__c = true;
                update s3FileToDelete;
            } else {
                System.debug('Error: ' + res.getStatusCode() + ' ' + res.getStatus());
                System.debug('Response Body: ' + res.getBody());
            }
    
        } catch (Exception e) {
            System.debug('Exception: ' + e.getMessage());
        }
    
        return isDeleted;
    }
    
    /**
     * Lists files for the specified S3 path prefix.
     * @param prefix S3 path prefix.
     * @return List of File objects.
    */
    @AuraEnabled
    public static List<File> listFiles(String prefix) {

        AWS_S3_Setting__mdt creds = getCreds('');

        String accessKey = creds.Access_Key__c;
        String secretKey = creds.Secret_Access_Key__c;
        String bucketName =  creds.Bucket__c;
        String bucketRegion = creds.Region__c; 

        List<String> fileNames = new List<String>();

        String endpoint = 'https://' + bucketName + '.s3.' + bucketRegion + '.amazonaws.com/?prefix=' + EncodingUtil.urlEncode(prefix, 'UTF-8');
        HttpRequest req = new HttpRequest();
            req.setMethod('GET');
            req.setEndpoint(endpoint);

        // Add AWS Signature (for simplicity, you might need to use a library or custom implementation)
        String dateString = Datetime.now().formatGMT('EEE, dd MMM yyyy HH:mm:ss') + ' GMT';
            req.setHeader('Date', dateString);

        // Authorization header: AWS <AccessKey>:<Signature>
        String stringToSign = 'GET\n\n\n' + dateString + '\n/' + bucketName + '/';
        String signature = EncodingUtil.base64Encode(Crypto.generateMac('HmacSHA1', Blob.valueOf(stringToSign), Blob.valueOf(secretKey)));
            req.setHeader('Authorization', 'AWS ' + accessKey + ':' + signature);

        Http http = new Http();
        HttpResponse res = http.send(req);

        Dom.Document doc = res.getBodyDocument();
        System.debug(doc);
        //Retrieve the root element for this document.
        Dom.XMLNode result = doc.getRootElement();
        
        List<File> files = new List<File>();

        // loop through the child elements.
        // deserialize the Contents xml into a list of files
        for (Dom.XMLNode child : result.getChildElements()) {
           
           System.debug(child);
          
           File file = new File();
           
            for (Dom.XMLNode content : child.getChildElements()){
                System.debug(content.getName() + ' => ' + content.getText());
                file.put(content.getName(), content.getText());
            }

            if (file.get('Key') != null) {
                files.add(file);
            }
        }

        System.debug('Files found: ' + files.size());
        System.debug('Files: ' + files);
        System.debug(files);
        return files;
    }

    /**
     * Determines if instance is production
     * @return Boolean for production instance - true if prod.
    */
    private static Boolean isProd() {
        Organization org = [
            SELECT Id, Name, IsSandbox 
            FROM Organization
        ];

        return !org.IsSandbox;
    }

    /**
     * Encodes aws key
     * @return String - encodedKey.
    */
    private static String encodeS3Key(String key) {
    
        String encoded = EncodingUtil.urlEncode(key, 'UTF-8');
    
        encoded = encoded.replace('+', '%20');
        
        encoded = encoded.replace('%2F', '/');
        return encoded;
    }


    /**
     * Generates a presigned URL for S3 operations.
     * @param method HTTP method (GET, PUT, DELETE).
     * @param key S3 key for the file.
     * @return Presigned URL string.
    */
    private static String createPresignedUrl(String method, String key) {
        AWS_S3_Setting__mdt creds = getCreds('');

        String accessKey = creds.Access_Key__c;
        String secretKey = creds.Secret_Access_Key__c;
        String bucketName =  creds.Bucket__c;
        String bucketRegion = creds.Region__c; 

        String encodedKey = encodeS3Key(key);

        // String location = createBaseUrl(creds) + key;
        String location = createBaseUrl(creds) + encodedKey;

        DateTime currentDateTime = DateTime.now();
        String dateOnly = currentDateTime.formatGmt('yyyyMMdd');
        String req =  dateOnly + '/'+ bucketRegion +'/s3/aws4_request';
        String xAmzCredentialStr = accessKey + '/' + req;
        String xAmzDate = currentDateTime.formatGmt('yyyyMMdd\'T\'HHmmss\'Z\'');
        String xAmzSignedHeaders = 'host';
        String host = bucketName + '.s3.'+ bucketRegion +'.amazonaws.com';

        // String canonicalRequest = method + '\n'+'/' + key + '\n';
        // String encodedKey = EncodingUtil.urlEncode(key, 'UTF-8').replace('+', '%20');
        String canonicalRequest = method + '\n'+'/' + encodedKey + '\n';
        
        canonicalRequest += UriEncode('X-Amz-Algorithm', true) + '=' + UriEncode('AWS4-HMAC-SHA256', true) + '&' +
            UriEncode('X-Amz-Credential', true) + '=' + UriEncode(xAmzCredentialStr, true) + '&' +
            UriEncode('X-Amz-Date', true) + '=' + UriEncode(xAmzDate, true) + '&' +
            UriEncode('X-Amz-Expires', true) + '=' + UriEncode(String.valueOf(PRESIGNED_URL_EXPIRES), true) + '&' +
            UriEncode('X-Amz-SignedHeaders', true) + '=' + UriEncode(xAmzSignedHeaders, true) + '\n';

            canonicalRequest += 'host:'+host + '\n\n' +
            'host\n' +
            'UNSIGNED-PAYLOAD';
     
        String stringToSign = 'AWS4-HMAC-SHA256\n' +
            xAmzDate + '\n' +
            req + '\n' +
            EncodingUtil.convertToHex(
                Crypto.generateDigest('SHA-256', Blob.valueOf(canonicalRequest))
            );
		
        Blob dateKey = Crypto.generateMac('hmacSHA256', Blob.valueOf(dateOnly), Blob.valueOf('AWS4' + secretKey));
        Blob dateRegionKey = Crypto.generateMac('hmacSHA256', Blob.valueOf(bucketRegion), dateKey);
        Blob dateRegionServiceKey = Crypto.generateMac('hmacSHA256', Blob.valueOf('s3'), dateRegionKey);
        Blob signingKey = Crypto.generateMac('hmacSHA256', Blob.valueOf('aws4_request'), dateRegionServiceKey);
     
        Blob signature = Crypto.generateMac('hmacSHA256', Blob.valueOf(stringToSign), signingKey);
        String signatureStr = EncodingUtil.convertToHex(signature);
     
        String result = location + 
        '?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=' + EncodingUtil.urlEncode(xAmzCredentialStr, 'UTF-8') + 
        '&X-Amz-Date=' + xAmzDate + 
        '&X-Amz-Expires=' + String.valueOf(PRESIGNED_URL_EXPIRES) + 
        '&X-Amz-Signature=' + signatureStr + '&X-Amz-SignedHeaders=host';

		return result;
    }

    /**
     * Retrieves AWS S3 credentials from custom metadata.
     * @param cred DeveloperName for the credential record.
     * @return AWS_S3_Setting__mdt record.
    */
    private static AWS_S3_Setting__mdt getCreds(String cred) {

        Boolean isProd = isProd();

        system.debug('isProd');
        system.debug(isProd);

        String query = 'SELECT '
                + 'Id, '
                + 'DeveloperName, '
                + 'Bucket__c, '
                + 'Identity_Pool_Id__c, '
                + 'Region__c, '
                + 'Access_Key__c, '
                + 'Production__c, '
                + 'Secret_Access_Key__c '
            + 'FROM AWS_S3_Setting__mdt ' 
            + ' WHERE Production__c =: isProd';

        if (cred != null && cred != '') {
            query += ' AND DeveloperName = \'' + String.escapeSingleQuotes(cred) + '\'';
        }

        query += ' LIMIT 1';
        
        AWS_S3_Setting__mdt credentials = Database.query(query);

        system.debug('credentials');
        system.debug('credentials.DeveloperName ' + credentials.DeveloperName);
        system.debug('credentials.Bucket__c ' + credentials.Bucket__c);
        system.debug('credentials.Region__c ' + credentials.Region__c);
        system.debug('credentials.Production__c ' + credentials.Production__c);

        return credentials;
    }

    /**
     * Retrieves AWS S3 Org wide File size limit from custom metadata.
     * @param cred DeveloperName for the credential record.
     * @return AWS_S3_Setting__mdt record.
    */
    @AuraEnabled
    public static AWS_S3_Setting__mdt getFileSizeLimit(String cred) {

        String query = 'SELECT '
                + 'Id, '
                + 'DeveloperName, '
                + 'File_Size_Limit_Mb__c '
            + 'FROM AWS_S3_Setting__mdt';

        if (cred != null && cred != '') {
            query += ' WHERE DeveloperName = \'' + String.escapeSingleQuotes(cred) + '\'';
        }

        query += ' LIMIT 1';

        AWS_S3_Setting__mdt credentials = Database.query(query);

        return credentials;
    }
    
    /**
     * Gets the API name of a Salesforce record.
     * @param recordId Salesforce record Id.
     * @return API name string.
    */
    @AuraEnabled
    public static string getRecordApiName(Id recordId) {
        return recordId.getSObjectType().getDescribe().getName();
    }

    /**
     * Creates the base S3 URL from credentials.
     * @param cred AWS_S3_Setting__mdt record.
     * @return Base S3 URL string.
    */
    private static String createBaseUrl(AWS_S3_Setting__mdt cred) {
        return 'https://' + cred.Bucket__c + '.s3.' + cred.Region__c + '.amazonaws.com/';
    }

    /**
     * Encodes a string for S3 URI requirements. Apex EncodingUtil.urlEncode differs from AWS S3 documentation Uri encoding
     * @param input String to encode.
     * @param encodeSlash Whether to encode slashes.
     * @return Encoded string.
    */
    private static String UriEncode(String input, Boolean encodeSlash) {
        String result = '';
    
        for (Integer i = 0; i < input.length(); i++) {
            String ch = input.substring(i, i + 1);
    
            if ((ch >= 'A' && ch <= 'Z') || (ch >= 'a'
               && ch <= 'z') || (ch >= '0' && ch <= '9') || ch == '_' ||
               ch == '-' || ch == '~' || ch == '.') {
               result += ch;
            } else if (ch == '/') {
               result += encodeSlash ? '%2F' : ch;
            } else {
                String hexValue = EncodingUtil.convertToHex(Blob.valueOf(ch)).toUpperCase();
    
                if (hexValue.length() == 2) {
                    result += '%' + hexValue;
                } else if (hexValue.length() == 4) {
                    result += '%' + hexValue.substring(0, 2) + '%' + hexValue.substring(2);
                }
            }
        }
    
       return result;
    }

    /**
     * Generates the signature key for AWS V4 signing.
     * @param key Secret key.
     * @param dateStamp Date stamp.
     * @param regionName AWS region.
     * @param serviceName AWS service name.
     * @return Signing key as Blob.
    */
    @testVisible
    private static Blob getSignatureKey(String key, String dateStamp, String regionName, String serviceName) {
        Blob kDate = Crypto.generateMac('HMACSHA256', Blob.valueOf(dateStamp), Blob.valueOf('AWS4' + key));
        Blob kRegion = Crypto.generateMac('HMACSHA256', Blob.valueOf(regionName), kDate);
        Blob kService = Crypto.generateMac('HMACSHA256', Blob.valueOf(serviceName), kRegion);
        Blob kSigning = Crypto.generateMac('HMACSHA256', Blob.valueOf('aws4_request'), kService);
        return kSigning;
    }

    /**
     * File wrapper class for S3 file metadata.
    */
    public class File {
        @AuraEnabled public String Name;
        @AuraEnabled public String Key;
        @AuraEnabled public String LastModified;
        @AuraEnabled public String ETag;
        @AuraEnabled public String Size;
        @AuraEnabled public String StorageClass;

        public void put(String key, String value){
            if(key == 'Key') {
                this.Key = value;
                this.Name = value.substring(value.lastIndexOf('/')+1);
            }
            if(key == 'LastModified') this.LastModified = value;
            if(key == 'ETag') this.ETag = value;
            if(key == 'Size') this.Size = value;
            if(key == 'StorageClass') this.StorageClass = value;
        }

        public String get(String key){
            if(key == 'Key') return this.Key;
            if(key == 'Name') return this.Name;
            if(key == 'LastModified') return this.LastModified;
            if(key == 'ETag') return this.ETag;
            if(key == 'Size') return this.Size;
            if(key == 'StorageClass') return this.StorageClass;
            return '';
        }
    }

    /**
     * Creates or updates a Salesforce S3 file record.
     * @param s3File S3_File__c record.
     * @return Created or updated S3_File__c record.
    */
    @AuraEnabled
    public static S3_File__c createSalesforceS3File(S3_File__c s3File) {

        system.debug('s3File');
        system.debug(s3File);

        List<S3_File__c> existingS3Files = [
            SELECT Id,
                Versions__c
            FROM S3_File__c
            WHERE Parent_Id__c =: s3File.Parent_Id__c
                AND sObject_Type__c =: s3File.sObject_Type__c
                AND Key__c =: s3File.Key__c
                AND Object_URL__c =: s3File.Object_URL__c
                AND Deleted__c = false
        ];

        if (existingS3Files.isEmpty()) {
                s3File.Versions__c = 1;
            insert s3File;
            return s3File;
        } else {
            S3_File__c existingS3File = existingS3Files[0];
                existingS3File.Versions__c = existingS3File.Versions__c + 1;
            update existingS3File;
            return existingS3File;
        }
    }

    /**
     * Retrieves Salesforce S3 file records for a given record Id.
     * @param recordId Salesforce record Id.
     * @param visibility top level bucket the files are contained in.
     * @return List of S3_File__c records.
    */
    @AuraEnabled
    public static List<S3_File__c> getSalesforceS3Files(Id recordId, String visibility) {

        String sObjectDeveloperName = recordId.getSObjectType().getDescribe().getName();

        return [
            SELECT Id,
                Parent_Id__c,
                File_Info__c,
                Visibility__c,
                File_Extension__c,
                sObject_Type__c,
                Versions__c,
                File_Name__c,
                CreatedDate,
                S3_Path__c,
                File_Last_Modified_Epoch__c,
                File_Last_Modified_Date__c,
                Key__c,
                Size_Label__c,
                Size_Bytes__c,
                Size_Kilobytes__c,
                Size_Megabytes__c,
                Type__c,
                Object_URL__c,
                Deleted__c
            FROM S3_File__c
            WHERE Parent_Id__c =: recordId 
                AND sObject_Type__c =: sObjectDeveloperName   
                AND Visibility__c =: visibility
                AND Deleted__c = false
            ORDER BY CreatedDate DESC
        ];
    }

    /**
     * Retrieves Salesforce S3 file records for a given record Id.
     * @param recordId Salesforce record Id.
     * @param path Path to files.
     * @return List of S3_File__c records.
    */
    @AuraEnabled
    public static List<S3_File__c> getSalesforceApplicationS3Files(
        Id recordId, 
        String path
    ) {

        String sObjectDeveloperName = recordId.getSObjectType().getDescribe().getName();

        return [
            SELECT Id,
                Parent_Id__c,
                File_Info__c,
                File_Extension__c,
                sObject_Type__c,
                Versions__c,
                File_Name__c,
                CreatedDate,
                S3_Path__c,
                File_Last_Modified_Epoch__c,
                File_Last_Modified_Date__c,
                Key__c,
                Size_Label__c,
                Size_Bytes__c,
                Size_Kilobytes__c,
                Size_Megabytes__c,
                Type__c,
                Object_URL__c,
                Deleted__c
            FROM S3_File__c
            WHERE Parent_Id__c =: recordId 
                AND sObject_Type__c =: sObjectDeveloperName   
                AND S3_Path__c =: path
                AND Visibility__c = 'external'
                AND Deleted__c = false
            ORDER BY CreatedDate DESC
        ];
    }
}